const messages = {
  'en-IN': {
    chooseLanguage:'Choose your language', languageHint:'Tap the language you speak.', whoAreYou:'Who are you?', artisan:'Artisan', buyer:'Buyer', artisanHelp:'Add and sell your handmade products', buyerHelp:'Find products and contact artisans', changeLanguage:'Change language',
    goodMorning:'Welcome', sellerIntro:'Your craft can reach more buyers.', support:'Your craft. More customers.', growTogether:'Let’s grow together', addProduct:'Add a product', startVoice:'Tell us about a product', yourShop:'Your shop', quickAccess:'Quick actions', manageCatalog:'See your products', trackSales:'See your orders', respondBuyers:'Reply to buyers', viewProfile:'Your details', recentActivity:'Next step', shopReady:'Your shop is ready for a product', addReach:'Add a product to show it to buyers.', myProducts:'My products', managePieces:'See and update your handmade products.', active:'Active', draft:'Draft', outOfStock:'Out of stock', pieces:'pieces',
    buyerHero:'Find handmade products', buyerIntro:'See the story behind each product.', explore:'Browse products', shopByCraft:'Browse by craft', findCraft:'Choose a craft', allCrafts:'All crafts', featured:'Featured products', recentlyAdded:'New products', viewAll:'See all', searchPlaceholder:'Search products or artisans', search:'Search', clear:'Clear', exploreCrafts:'Browse products', finds:'products', find:'product', trySearch:'Try another search.', noProducts:'No products yet', keepCraft:'Support local craft', keepCraftText:'Meet artisans and discover the work they make.',
    productStory:'Product story', productDetails:'Product details', material:'Material', color:'Color', size:'Size', madeBy:'Made by', madeIn:'Made in India', available:'available', shipNote:'Ships with care from the artisan.', unavailable:'Not available now', addCart:'Add to cart', buyNow:'Buy now', contactArtisan:'Contact artisan', sendEnquiry:'Send an enquiry', bulkRequest:'Ask about a bulk order', yourName:'Your name', buyerName:'Your name or business', buyerType:'I am a', quantity:'How many do you need?', targetPrice:'Your price per piece (optional)', message:'Message', messageHint:'Tell the artisan what you need.', retailer:'Shop owner', wholesaler:'Wholesale buyer', bulkBuyer:'Bulk buyer', onlineSeller:'Online seller', corporateBuyer:'Company buyer', procurement:'Organization', sending:'Sending…', send:'Send enquiry',
    cart:'Cart', myCart:'My cart', orderSummary:'Order total', subtotal:'Subtotal', shipping:'Delivery', free:'Free', total:'Total', placeOrder:'Place order', emptyCart:'Your cart is empty', emptyCartHint:'Browse products and add one you like.', orderSuccess:'Order placed.', addedToCart:'Added to your cart.',
    buyerEnquiries:'Buyer enquiries', noEnquiries:'No enquiries yet', enquiriesHint:'Buyer requests will appear here.', decline:'Decline', acceptOrder:'Accept and make order', markPending:'Mark as waiting', markComplete:'Mark complete', incomingOrders:'New orders', myOrders:'My orders', noOrders:'No orders yet', ordersHint:'Orders will appear here.', placed:'Placed', markShipped:'Mark sent', markDelivered:'Mark delivered', statusUpdated:'Order updated.',
    profile:'Profile', sellerRole:'ARTISAN', buyerRole:'BUYER', member:'Member', saveProfile:'Save details', editProfile:'Edit details', marketplaceExperience:'Choose how to use Martisan', switchHint:'Change between selling and shopping.', switchToArtisan:'Go to artisan', switchToBuyer:'Go to buyer', backWelcome:'Choose another role', myAddresses:'My addresses', help:'Help', about:'About Martisan', profileSaved:'Details saved.', shopProfile:'Artisan details', viewShop:'View artisan',
    demoMode:'Demo mode', demoHint:'AI is not connected. You can still try the app.', retry:'Try again', useOriginal:'Use original photo', originalReady:'Using your original photo.', cameraPreview:'Preview photo', retake:'Take another', usePhoto:'Use this photo', catalogDemo:'Demo catalog only. AI is offline; check these details before using them.', catalogDemoName:'Handmade product', catalogDemoDescription:'Add the material, design, and making details you know. This demo catalog does not analyze the photo.', catalogDemoHindi:'यह केवल डेमो कैटलॉग है। फोटो का AI विश्लेषण नहीं हुआ। सामग्री और डिज़ाइन की जानकारी जाँचकर जोड़ें।',
    priceFailed:'Price help is unavailable. You can enter your price.', priceHelp:'Help me set a price', priceSuggested:'Suggested price', usePrice:'Use this price', language:'Language', cancel:'Cancel', done:'Done', error:'Something went wrong. Please try again.'
  },
  'ta-IN': {
    chooseLanguage:'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்', languageHint:'நீங்கள் பேசும் மொழியைத் தொடவும்.', whoAreYou:'நீங்கள் யார்?', artisan:'கைவினைஞர்', buyer:'வாங்குபவர்', artisanHelp:'உங்கள் கைவினைப் பொருட்களைச் சேர்த்து விற்கவும்', buyerHelp:'பொருட்களைப் பார்த்து கைவினைஞர்களைத் தொடர்புகொள்ளவும்', changeLanguage:'மொழியை மாற்றவும்',
    goodMorning:'வணக்கம்', sellerIntro:'உங்கள் கைவினை மேலும் வாங்குபவர்களைச் சென்றடையட்டும்.', support:'உங்கள் கைவினை. மேலும் வாடிக்கையாளர்கள்.', growTogether:'ஒன்றாக வளர்வோம்', addProduct:'பொருளைச் சேர்க்கவும்', startVoice:'பொருளைப் பற்றிச் சொல்லுங்கள்', yourShop:'உங்கள் கடை', quickAccess:'விரைவு செயல்கள்', manageCatalog:'உங்கள் பொருட்களைப் பார்க்கவும்', trackSales:'ஆர்டர்களைப் பார்க்கவும்', respondBuyers:'வாங்குபவர்களுக்குப் பதிலளிக்கவும்', viewProfile:'உங்கள் விவரங்கள்', recentActivity:'அடுத்த செயல்', shopReady:'உங்கள் கடையில் பொருள் சேர்க்கலாம்', addReach:'வாங்குபவர்கள் பார்க்க ஒரு பொருளைச் சேர்க்கவும்.', myProducts:'என் பொருட்கள்', managePieces:'உங்கள் கைவினைப் பொருட்களைப் பார்க்கவும் மாற்றவும்.', active:'செயலில்', draft:'வரைவு', outOfStock:'கையிருப்பில் இல்லை', pieces:'பொருட்கள்',
    buyerHero:'கைவினைப் பொருட்களைக் கண்டறியுங்கள்', buyerIntro:'ஒவ்வொரு பொருளின் கதையையும் பாருங்கள்.', explore:'பொருட்களைப் பார்க்கவும்', shopByCraft:'கைவினை வகையில் பார்க்கவும்', findCraft:'ஒரு கைவினையைத் தேர்ந்தெடுக்கவும்', allCrafts:'அனைத்து கைவினைகள்', featured:'சிறப்பு பொருட்கள்', recentlyAdded:'புதிய பொருட்கள்', viewAll:'அனைத்தையும் பார்க்கவும்', searchPlaceholder:'பொருள் அல்லது கைவினைஞரைத் தேடுங்கள்', search:'தேடுங்கள்', clear:'அழிக்கவும்', exploreCrafts:'பொருட்களைப் பார்க்கவும்', finds:'பொருட்கள்', find:'பொருள்', trySearch:'வேறு சொல்லைத் தேடுங்கள்.', noProducts:'இன்னும் பொருட்கள் இல்லை', keepCraft:'உள்ளூர் கைவினையை ஆதரிக்கவும்', keepCraftText:'கைவினைஞர்களையும் அவர்களின் படைப்புகளையும் அறியுங்கள்.',
    productStory:'பொருளின் கதை', productDetails:'பொருள் விவரங்கள்', material:'பொருள்', color:'நிறம்', size:'அளவு', madeBy:'செய்தவர்', madeIn:'இந்தியாவில் தயாரிக்கப்பட்டது', available:'கிடைக்கும்', shipNote:'கைவினைஞர் கவனமாக அனுப்புவார்.', unavailable:'இப்போது கிடைக்காது', addCart:'கூடையில் சேர்க்கவும்', buyNow:'வாங்கவும்', contactArtisan:'கைவினைஞரைத் தொடர்புகொள்ளவும்', sendEnquiry:'விசாரணை அனுப்பவும்', bulkRequest:'மொத்த ஆர்டர் பற்றி கேளுங்கள்', yourName:'உங்கள் பெயர்', buyerName:'உங்கள் பெயர் அல்லது நிறுவனம்', buyerType:'நான் ஒரு', quantity:'எத்தனை வேண்டும்?', targetPrice:'ஒரு பொருளுக்கான விலை (விருப்பம்)', message:'செய்தி', messageHint:'உங்களுக்கு என்ன வேண்டும் என்று சொல்லுங்கள்.', retailer:'கடை உரிமையாளர்', wholesaler:'மொத்த விற்பனையாளர்', bulkBuyer:'மொத்த வாங்குபவர்', onlineSeller:'ஆன்லைன் விற்பனையாளர்', corporateBuyer:'நிறுவனம்', procurement:'அமைப்பு', sending:'அனுப்புகிறது…', send:'விசாரணை அனுப்பவும்',
    cart:'கூடை', myCart:'என் கூடை', orderSummary:'ஆர்டர் மொத்தம்', subtotal:'பொருட்களின் விலை', shipping:'அனுப்புதல்', free:'இலவசம்', total:'மொத்தம்', placeOrder:'ஆர்டர் செய்யவும்', emptyCart:'கூடை காலியாக உள்ளது', emptyCartHint:'பொருட்களைப் பார்த்து ஒன்றைச் சேர்க்கவும்.', orderSuccess:'ஆர்டர் செய்யப்பட்டது.', addedToCart:'கூடையில் சேர்க்கப்பட்டது.',
    buyerEnquiries:'வாங்குபவர் விசாரணைகள்', noEnquiries:'இன்னும் விசாரணைகள் இல்லை', enquiriesHint:'வாங்குபவர்களின் கோரிக்கைகள் இங்கே வரும்.', decline:'நிராகரிக்கவும்', acceptOrder:'ஏற்று ஆர்டர் உருவாக்கவும்', markPending:'காத்திருக்கிறது எனக் குறிக்கவும்', markComplete:'முடிந்தது எனக் குறிக்கவும்', incomingOrders:'புதிய ஆர்டர்கள்', myOrders:'என் ஆர்டர்கள்', noOrders:'இன்னும் ஆர்டர்கள் இல்லை', ordersHint:'ஆர்டர்கள் இங்கே வரும்.', placed:'செய்த நாள்', markShipped:'அனுப்பியதாகக் குறிக்கவும்', markDelivered:'வழங்கியதாகக் குறிக்கவும்', statusUpdated:'ஆர்டர் மாற்றப்பட்டது.',
    profile:'சுயவிவரம்', sellerRole:'கைவினைஞர்', buyerRole:'வாங்குபவர்', member:'உறுப்பினர்', saveProfile:'விவரங்களைச் சேமிக்கவும்', editProfile:'விவரங்களை மாற்றவும்', marketplaceExperience:'Martisan-ஐ எப்படிப் பயன்படுத்துவது?', switchHint:'விற்பனை மற்றும் வாங்குதலுக்கு மாறலாம்.', switchToArtisan:'கைவினைஞராகச் செல்லவும்', switchToBuyer:'வாங்குபவராகச் செல்லவும்', backWelcome:'மற்றொரு பங்கைத் தேர்ந்தெடுக்கவும்', myAddresses:'என் முகவரிகள்', help:'உதவி', about:'Martisan பற்றி', profileSaved:'விவரங்கள் சேமிக்கப்பட்டன.', shopProfile:'கைவினைஞர் விவரங்கள்', viewShop:'கைவினைஞரைப் பார்க்கவும்',
    demoMode:'டெமோ முறை', demoHint:'AI இணைக்கப்படவில்லை. பயன்பாட்டைப் பயன்படுத்திப் பார்க்கலாம்.', retry:'மீண்டும் முயற்சிக்கவும்', useOriginal:'அசல் படத்தைப் பயன்படுத்தவும்', originalReady:'அசல் படம் பயன்படுத்தப்படுகிறது.', cameraPreview:'படத்தை முன்னோட்டமிடுங்கள்', retake:'மீண்டும் படம் எடுக்கவும்', usePhoto:'இந்தப் படத்தைப் பயன்படுத்தவும்', catalogDemo:'டெமோ பட்டியல் மட்டும். AI இயங்கவில்லை; பயன்படுத்தும் முன் விவரங்களைச் சரிபார்க்கவும்.', catalogDemoName:'கைவினைப் பொருள்', catalogDemoDescription:'உங்களுக்குத் தெரிந்த பொருள், வடிவம், தயாரிப்பு விவரங்களைச் சேர்க்கவும். இந்த டெமோ படம் பகுப்பாய்வு செய்யாது.', catalogDemoHindi:'यह केवल डेमो कैटलॉग है। फोटो का AI विश्लेषण नहीं हुआ। सामग्री और डिज़ाइन की जानकारी जाँचकर जोड़ें।',
    priceFailed:'விலை உதவி கிடைக்கவில்லை. உங்கள் விலையை உள்ளிடலாம்.', priceHelp:'விலை அமைக்க உதவுங்கள்', priceSuggested:'பரிந்துரைத்த விலை', usePrice:'இந்த விலையைப் பயன்படுத்தவும்', language:'மொழி', cancel:'ரத்து', done:'முடிந்தது', error:'ஏதோ தவறு ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.'
  },
  'hi-IN': {
    chooseLanguage:'अपनी भाषा चुनें', languageHint:'जिस भाषा में आप बात करते हैं, उसे चुनें।', whoAreYou:'आप कौन हैं?', artisan:'कारीगर', buyer:'खरीदार', artisanHelp:'अपने हाथ से बने उत्पाद जोड़ें और बेचें', buyerHelp:'उत्पाद देखें और कारीगरों से बात करें', changeLanguage:'भाषा बदलें',
    goodMorning:'नमस्ते', sellerIntro:'आपका हुनर और खरीदारों तक पहुँचे।', support:'आपका हुनर। और ग्राहक।', growTogether:'आइए साथ बढ़ें', addProduct:'उत्पाद जोड़ें', startVoice:'उत्पाद के बारे में बोलें', yourShop:'आपकी दुकान', quickAccess:'जल्दी करें', manageCatalog:'अपने उत्पाद देखें', trackSales:'अपने ऑर्डर देखें', respondBuyers:'खरीदारों को जवाब दें', viewProfile:'आपकी जानकारी', recentActivity:'अगला काम', shopReady:'दुकान में उत्पाद जोड़ें', addReach:'खरीदारों को दिखाने के लिए उत्पाद जोड़ें।', myProducts:'मेरे उत्पाद', managePieces:'अपने हाथ से बने उत्पाद देखें और बदलें।', active:'चालू', draft:'मसौदा', outOfStock:'स्टॉक में नहीं', pieces:'उत्पाद',
    buyerHero:'हाथ से बने उत्पाद खोजें', buyerIntro:'हर उत्पाद की कहानी जानें।', explore:'उत्पाद देखें', shopByCraft:'कारीगरी के अनुसार देखें', findCraft:'कारीगरी चुनें', allCrafts:'सभी कारीगरी', featured:'खास उत्पाद', recentlyAdded:'नए उत्पाद', viewAll:'सभी देखें', searchPlaceholder:'उत्पाद या कारीगर खोजें', search:'खोजें', clear:'साफ़ करें', exploreCrafts:'उत्पाद देखें', finds:'उत्पाद', find:'उत्पाद', trySearch:'दूसरा शब्द खोजें।', noProducts:'अभी कोई उत्पाद नहीं', keepCraft:'स्थानीय कारीगरी का साथ दें', keepCraftText:'कारीगरों और उनके काम से मिलें।',
    productStory:'उत्पाद की कहानी', productDetails:'उत्पाद की जानकारी', material:'सामग्री', color:'रंग', size:'आकार', madeBy:'कारीगर', madeIn:'भारत में बना', available:'उपलब्ध', shipNote:'कारीगर इसे ध्यान से भेजेंगे।', unavailable:'अभी उपलब्ध नहीं', addCart:'कार्ट में डालें', buyNow:'अभी खरीदें', contactArtisan:'कारीगर से बात करें', sendEnquiry:'पूछताछ भेजें', bulkRequest:'थोक ऑर्डर के बारे में पूछें', yourName:'आपका नाम', buyerName:'आपका या कारोबार का नाम', buyerType:'मैं हूँ', quantity:'कितने चाहिए?', targetPrice:'एक उत्पाद की कीमत (ज़रूरी नहीं)', message:'संदेश', messageHint:'कारीगर को अपनी ज़रूरत बताएं।', retailer:'दुकानदार', wholesaler:'थोक खरीदार', bulkBuyer:'थोक खरीदार', onlineSeller:'ऑनलाइन विक्रेता', corporateBuyer:'कंपनी', procurement:'संस्था', sending:'भेज रहे हैं…', send:'पूछताछ भेजें',
    cart:'कार्ट', myCart:'मेरा कार्ट', orderSummary:'ऑर्डर की कुल कीमत', subtotal:'उप-योग', shipping:'डिलीवरी', free:'मुफ़्त', total:'कुल', placeOrder:'ऑर्डर करें', emptyCart:'कार्ट खाली है', emptyCartHint:'उत्पाद देखें और पसंद का उत्पाद जोड़ें।', orderSuccess:'ऑर्डर हो गया।', addedToCart:'कार्ट में डाल दिया।',
    buyerEnquiries:'खरीदार की पूछताछ', noEnquiries:'अभी पूछताछ नहीं है', enquiriesHint:'खरीदारों की माँग यहाँ दिखेगी।', decline:'मना करें', acceptOrder:'स्वीकार कर ऑर्डर बनाएं', markPending:'रुका हुआ चिह्नित करें', markComplete:'पूरा चिह्नित करें', incomingOrders:'नए ऑर्डर', myOrders:'मेरे ऑर्डर', noOrders:'अभी ऑर्डर नहीं हैं', ordersHint:'आपके ऑर्डर यहाँ दिखेंगे।', placed:'तारीख', markShipped:'भेजा हुआ चिह्नित करें', markDelivered:'पहुँचा हुआ चिह्नित करें', statusUpdated:'ऑर्डर अपडेट हुआ।',
    profile:'प्रोफ़ाइल', sellerRole:'कारीगर', buyerRole:'खरीदार', member:'सदस्य', saveProfile:'जानकारी सहेजें', editProfile:'जानकारी बदलें', marketplaceExperience:'Martisan कैसे इस्तेमाल करें', switchHint:'बेचने और खरीदने के बीच बदलें।', switchToArtisan:'कारीगर बनें', switchToBuyer:'खरीदार बनें', backWelcome:'दूसरी भूमिका चुनें', myAddresses:'मेरे पते', help:'मदद', about:'Martisan के बारे में', profileSaved:'जानकारी सहेजी।', shopProfile:'कारीगर की जानकारी', viewShop:'कारीगर देखें',
    demoMode:'डेमो मोड', demoHint:'AI जुड़ा नहीं है। आप ऐप को आज़मा सकते हैं।', retry:'फिर कोशिश करें', useOriginal:'मूल तस्वीर इस्तेमाल करें', originalReady:'मूल तस्वीर इस्तेमाल हो रही है।', cameraPreview:'तस्वीर देखें', retake:'दूसरी तस्वीर लें', usePhoto:'यह तस्वीर इस्तेमाल करें', catalogDemo:'केवल डेमो कैटलॉग। AI बंद है; जानकारी इस्तेमाल करने से पहले जाँचें।', catalogDemoName:'हाथ से बना उत्पाद', catalogDemoDescription:'जो सामग्री, डिज़ाइन और बनाने की जानकारी आपको पता है, वह जोड़ें। यह डेमो तस्वीर का विश्लेषण नहीं करता।', catalogDemoHindi:'यह केवल डेमो कैटलॉग है। फोटो का AI विश्लेषण नहीं हुआ। सामग्री और डिज़ाइन की जानकारी जाँचकर जोड़ें।',
    priceFailed:'कीमत में मदद नहीं मिली। आप अपनी कीमत लिख सकते हैं।', priceHelp:'कीमत तय करने में मदद करें', priceSuggested:'सुझाई कीमत', usePrice:'यह कीमत रखें', language:'भाषा', cancel:'रद्द करें', done:'हो गया', error:'कुछ गड़बड़ हुई। फिर कोशिश करें।'
  },
  'ml-IN': {
    chooseLanguage:'ഭാഷ തിരഞ്ഞെടുക്കുക', languageHint:'നിങ്ങൾ സംസാരിക്കുന്ന ഭാഷ തിരഞ്ഞെടുക്കൂ.', whoAreYou:'നിങ്ങൾ ആരാണ്?', artisan:'കരകൗശലക്കാരൻ', buyer:'വാങ്ങുന്നയാൾ', artisanHelp:'കൈകൊണ്ട് നിർമ്മിച്ച ഉൽപ്പന്നങ്ങൾ ചേർത്ത് വിൽക്കുക', buyerHelp:'ഉൽപ്പന്നങ്ങൾ കണ്ട് കരകൗശലക്കാരുമായി ബന്ധപ്പെടുക', changeLanguage:'ഭാഷ മാറ്റുക',
    goodMorning:'നമസ്കാരം', sellerIntro:'നിങ്ങളുടെ കരകൗശലം കൂടുതൽ ആളുകളിലെത്തട്ടെ.', support:'നിങ്ങളുടെ കരകൗശലം. കൂടുതൽ ഉപഭോക്താക്കൾ.', growTogether:'ഒന്നിച്ച് വളരാം', addProduct:'ഉൽപ്പന്നം ചേർക്കുക', startVoice:'ഉൽപ്പന്നത്തെക്കുറിച്ച് പറയൂ', yourShop:'നിങ്ങളുടെ കട', quickAccess:'വേഗത്തിലുള്ള കാര്യങ്ങൾ', manageCatalog:'ഉൽപ്പന്നങ്ങൾ കാണുക', trackSales:'ഓർഡറുകൾ കാണുക', respondBuyers:'വാങ്ങുന്നവർക്ക് മറുപടി നൽകുക', viewProfile:'നിങ്ങളുടെ വിവരങ്ങൾ', recentActivity:'അടുത്ത കാര്യം', shopReady:'കടയിൽ ഉൽപ്പന്നം ചേർക്കാം', addReach:'വാങ്ങുന്നവർക്ക് കാണാൻ ഒരു ഉൽപ്പന്നം ചേർക്കുക.', myProducts:'എന്റെ ഉൽപ്പന്നങ്ങൾ', managePieces:'ഉൽപ്പന്നങ്ങൾ കാണുകയും മാറ്റുകയും ചെയ്യുക.', active:'സജീവം', draft:'ഡ്രാഫ്റ്റ്', outOfStock:'സ്റ്റോക്കില്ല', pieces:'എണ്ണം',
    buyerHero:'കൈകൊണ്ട് നിർമ്മിച്ച ഉൽപ്പന്നങ്ങൾ കണ്ടെത്തൂ', buyerIntro:'ഓരോ ഉൽപ്പന്നത്തിന്റെയും കഥ അറിയൂ.', explore:'ഉൽപ്പന്നങ്ങൾ കാണുക', shopByCraft:'കരകൗശല പ്രകാരം കാണുക', findCraft:'കരകൗശലം തിരഞ്ഞെടുക്കുക', allCrafts:'എല്ലാ കരകൗശലങ്ങളും', featured:'തിരഞ്ഞെടുത്ത ഉൽപ്പന്നങ്ങൾ', recentlyAdded:'പുതിയ ഉൽപ്പന്നങ്ങൾ', viewAll:'എല്ലാം കാണുക', searchPlaceholder:'ഉൽപ്പന്നമോ കരകൗശലക്കാരനെയോ തിരയുക', search:'തിരയുക', clear:'മായ്ക്കുക', exploreCrafts:'ഉൽപ്പന്നങ്ങൾ കാണുക', finds:'ഉൽപ്പന്നങ്ങൾ', find:'ഉൽപ്പന്നം', trySearch:'മറ്റൊരു വാക്ക് തിരയുക.', noProducts:'ഇപ്പോൾ ഉൽപ്പന്നങ്ങളില്ല', keepCraft:'പ്രാദേശിക കരകൗശലത്തെ പിന്തുണയ്ക്കൂ', keepCraftText:'കരകൗശലക്കാരെയും അവരുടെ സൃഷ്ടികളെയും അറിയൂ.',
    productStory:'ഉൽപ്പന്നത്തിന്റെ കഥ', productDetails:'ഉൽപ്പന്ന വിവരങ്ങൾ', material:'വസ്തു', color:'നിറം', size:'വലുപ്പം', madeBy:'നിർമ്മിച്ചത്', madeIn:'ഇന്ത്യയിൽ നിർമ്മിച്ചത്', available:'ലഭ്യം', shipNote:'കരകൗശലക്കാരൻ ശ്രദ്ധയോടെ അയക്കും.', unavailable:'ഇപ്പോൾ ലഭ്യമല്ല', addCart:'കാർട്ടിൽ ചേർക്കുക', buyNow:'ഇപ്പോൾ വാങ്ങുക', contactArtisan:'കരകൗശലക്കാരനെ ബന്ധപ്പെടുക', sendEnquiry:'ചോദ്യം അയയ്ക്കുക', bulkRequest:'ബൾക്ക് ഓർഡറിനെക്കുറിച്ച് ചോദിക്കുക', yourName:'നിങ്ങളുടെ പേര്', buyerName:'നിങ്ങളുടെ പേര് അല്ലെങ്കിൽ ബിസിനസ്', buyerType:'ഞാൻ ഒരു', quantity:'എത്ര എണ്ണം വേണം?', targetPrice:'ഒരു ഉൽപ്പന്നത്തിന്റെ വില (ഐച്ഛികം)', message:'സന്ദേശം', messageHint:'നിങ്ങൾക്ക് എന്താണ് വേണ്ടതെന്ന് പറയുക.', retailer:'കടയുടമ', wholesaler:'മൊത്തവാങ്ങുന്നയാൾ', bulkBuyer:'ബൾക്ക് വാങ്ങുന്നയാൾ', onlineSeller:'ഓൺലൈൻ വിൽപ്പനക്കാരൻ', corporateBuyer:'കമ്പനി', procurement:'സ്ഥാപനം', sending:'അയക്കുന്നു…', send:'ചോദ്യം അയയ്ക്കുക',
    cart:'കാർട്ട്', myCart:'എന്റെ കാർട്ട്', orderSummary:'ഓർഡർ മൊത്തം', subtotal:'ഉപമൊത്തം', shipping:'ഡെലിവറി', free:'സൗജന്യം', total:'മൊത്തം', placeOrder:'ഓർഡർ ചെയ്യുക', emptyCart:'കാർട്ട് കാലിയാണ്', emptyCartHint:'ഉൽപ്പന്നങ്ങൾ കണ്ട് ഇഷ്ടമുള്ളത് ചേർക്കൂ.', orderSuccess:'ഓർഡർ ചെയ്തു.', addedToCart:'കാർട്ടിൽ ചേർത്തു.',
    buyerEnquiries:'വാങ്ങുന്നവരുടെ ചോദ്യങ്ങൾ', noEnquiries:'ഇപ്പോൾ ചോദ്യങ്ങളില്ല', enquiriesHint:'വാങ്ങുന്നവരുടെ ആവശ്യങ്ങൾ ഇവിടെ കാണാം.', decline:'നിരസിക്കുക', acceptOrder:'അംഗീകരിച്ച് ഓർഡർ ഉണ്ടാക്കുക', markPending:'കാത്തിരിപ്പായി അടയാളപ്പെടുത്തുക', markComplete:'പൂർത്തിയായതായി അടയാളപ്പെടുത്തുക', incomingOrders:'പുതിയ ഓർഡറുകൾ', myOrders:'എന്റെ ഓർഡറുകൾ', noOrders:'ഇപ്പോൾ ഓർഡറുകളില്ല', ordersHint:'ഓർഡറുകൾ ഇവിടെ കാണാം.', placed:'തീയതി', markShipped:'അയച്ചതായി അടയാളപ്പെടുത്തുക', markDelivered:'ലഭിച്ചതായി അടയാളപ്പെടുത്തുക', statusUpdated:'ഓർഡർ പുതുക്കി.',
    profile:'പ്രൊഫൈൽ', sellerRole:'കരകൗശലക്കാരൻ', buyerRole:'വാങ്ങുന്നയാൾ', member:'അംഗം', saveProfile:'വിവരങ്ങൾ സേവ് ചെയ്യുക', editProfile:'വിവരങ്ങൾ തിരുത്തുക', marketplaceExperience:'Martisan എങ്ങനെ ഉപയോഗിക്കാം', switchHint:'വിൽപ്പനയും വാങ്ങലും മാറാം.', switchToArtisan:'കരകൗശലക്കാരനായി മാറുക', switchToBuyer:'വാങ്ങുന്നയാളായി മാറുക', backWelcome:'മറ്റൊരു പങ്ക് തിരഞ്ഞെടുക്കുക', myAddresses:'എന്റെ വിലാസങ്ങൾ', help:'സഹായം', about:'Martisan വിവരങ്ങൾ', profileSaved:'വിവരങ്ങൾ സേവ് ചെയ്തു.', shopProfile:'കരകൗശലക്കാരന്റെ വിവരങ്ങൾ', viewShop:'കരകൗശലക്കാരനെ കാണുക',
    demoMode:'ഡെമോ മോഡ്', demoHint:'AI ബന്ധിപ്പിച്ചിട്ടില്ല. ആപ്പ് പരീക്ഷിക്കാം.', retry:'വീണ്ടും ശ്രമിക്കുക', useOriginal:'യഥാർത്ഥ ചിത്രം ഉപയോഗിക്കുക', originalReady:'യഥാർത്ഥ ചിത്രം ഉപയോഗിക്കുന്നു.', cameraPreview:'ചിത്രം പ്രിവ്യൂ ചെയ്യുക', retake:'വീണ്ടും എടുക്കുക', usePhoto:'ഈ ചിത്രം ഉപയോഗിക്കുക', catalogDemo:'ഡെമോ കാറ്റലോഗ് മാത്രം. AI പ്രവർത്തിക്കുന്നില്ല; ഉപയോഗിക്കുന്നതിന് മുമ്പ് വിവരങ്ങൾ പരിശോധിക്കുക.', catalogDemoName:'കൈകൊണ്ട് നിർമ്മിച്ച ഉൽപ്പന്നം', catalogDemoDescription:'അറിയാവുന്ന വസ്തു, ഡിസൈൻ, നിർമ്മാണ വിവരങ്ങൾ ചേർക്കുക. ഈ ഡെമോ ചിത്രം പരിശോധിക്കില്ല.', catalogDemoHindi:'यह केवल डेमो कैटलॉग है। फोटो का AI विश्लेषण नहीं हुआ। सामग्री और डिज़ाइन की जानकारी जाँचकर जोड़ें।',
    priceFailed:'വില നിർദ്ദേശം ലഭ്യമല്ല. നിങ്ങളുടെ വില നൽകാം.', priceHelp:'വില നിശ്ചയിക്കാൻ സഹായിക്കൂ', priceSuggested:'നിർദ്ദേശിച്ച വില', usePrice:'ഈ വില ഉപയോഗിക്കുക', language:'ഭാഷ', cancel:'റദ്ദാക്കുക', done:'കഴിഞ്ഞു', error:'ഒരു പ്രശ്നമുണ്ടായി. വീണ്ടും ശ്രമിക്കുക.'
  },
};

const sharedCopy = {
  'en-IN':{edit:'Edit',delete:'Delete',optional:'Optional',home:'Home',decrease:'Decrease quantity',increase:'Increase quantity',remove:'Remove',photoEnhanceFailed:"We couldn't improve the photo.",enhancedPreview:'Enhanced preview',acceptPhoto:'Use improved photo',photoAvailable:'Original photo is kept safely.',saved:'Saved',myEnquiries:'My Enquiries',saveProduct:'Save product',savedRemove:'Remove saved product',savedAdded:'Product saved',savedRemoved:'Removed from saved products',savedEmpty:'No saved products yet',savedHint:'Save products you want to ask an artisan about.',b2bMarketplace:'Discover artisan products · Ask about bulk orders',artisanProducts:'Products from artisans',recommendedProducts:'Recommended for you',productsByArtisan:'products by this artisan',Handloom:'Handloom',Handicrafts:'Handicrafts','Bamboo Craft':'Bamboo craft','Wood Craft':'Wood craft',Bags:'Bags',Traditional:'Traditional','Other Handmade Products':'Other handmade',products:'products',savedNav:'Saved',enquirySent:'Your enquiry was sent.',sent:'Sent',viewed:'Viewed',responded:'Responded',processing:'Processing',shipped:'Shipped',delivered:'Delivered',orderLabel:'ORDER',visualAnalysis:'Image observations'},
  'ta-IN':{edit:'திருத்து',delete:'நீக்கு',optional:'விருப்பம்',home:'முகப்பு',decrease:'எண்ணிக்கையைக் குறை',increase:'எண்ணிக்கையை அதிகரி',remove:'நீக்கு',photoEnhanceFailed:'படத்தை மேம்படுத்த முடியவில்லை.',enhancedPreview:'மேம்படுத்திய பட முன்னோட்டம்',acceptPhoto:'மேம்படுத்திய படத்தைப் பயன்படுத்து',photoAvailable:'அசல் படம் பாதுகாப்பாக உள்ளது.',saved:'சேமித்தவை',myEnquiries:'என் விசாரணைகள்',saveProduct:'பொருளைச் சேமி',savedRemove:'சேமித்ததிலிருந்து நீக்கு',savedAdded:'பொருள் சேமிக்கப்பட்டது',savedRemoved:'சேமித்த பொருட்களிலிருந்து நீக்கப்பட்டது',savedEmpty:'சேமித்த பொருட்கள் இல்லை',savedHint:'கைவினைஞரிடம் கேட்க விரும்பும் பொருட்களைச் சேமிக்கவும்.',b2bMarketplace:'கைவினைப் பொருட்களைக் கண்டறியுங்கள் · மொத்த ஆர்டர் கேளுங்கள்',artisanProducts:'கைவினைஞர்களின் பொருட்கள்',recommendedProducts:'உங்களுக்கான பரிந்துரைகள்',productsByArtisan:'இந்தக் கைவினைஞரின் பொருட்கள்',Handloom:'கைத்தறி',Handicrafts:'கைவினைப் பொருட்கள்','Bamboo Craft':'மூங்கில் கைவினை','Wood Craft':'மரக் கைவினை',Bags:'பைகள்',Traditional:'பாரம்பரியம்','Other Handmade Products':'மற்ற கைவினைப் பொருட்கள்',products:'பொருட்கள்',enquirySent:'உங்கள் விசாரணை அனுப்பப்பட்டது.',sent:'அனுப்பப்பட்டது',viewed:'பார்க்கப்பட்டது',responded:'பதிலளிக்கப்பட்டது',processing:'செயலாக்கத்தில்',shipped:'அனுப்பப்பட்டது',delivered:'வழங்கப்பட்டது',orderLabel:'ஆர்டர்',visualAnalysis:'படத்தில் தெரியும் விவரங்கள்'},
  'hi-IN':{edit:'बदलें',delete:'हटाएं',optional:'वैकल्पिक',home:'होम',decrease:'मात्रा घटाएं',increase:'मात्रा बढ़ाएं',remove:'हटाएं',photoEnhanceFailed:'तस्वीर बेहतर नहीं हो सकी।',enhancedPreview:'बेहतर तस्वीर देखें',acceptPhoto:'बेहतर तस्वीर इस्तेमाल करें',photoAvailable:'मूल तस्वीर सुरक्षित है।',saved:'सहेजे उत्पाद',myEnquiries:'मेरी पूछताछ',saveProduct:'उत्पाद सहेजें',savedRemove:'सहेजे से हटाएं',savedAdded:'उत्पाद सहेजा गया',savedRemoved:'सहेजे उत्पादों से हटाया गया',savedEmpty:'अभी कोई सहेजा उत्पाद नहीं',savedHint:'जिन उत्पादों के बारे में कारीगर से पूछना है, उन्हें सहेजें।',b2bMarketplace:'कारीगर उत्पाद खोजें · थोक ऑर्डर पूछें',productsByArtisan:'इस कारीगर के उत्पाद',Handloom:'हथकरघा',Handicrafts:'हस्तशिल्प','Bamboo Craft':'बांस शिल्प','Wood Craft':'लकड़ी का शिल्प',Bags:'बैग',Traditional:'पारंपरिक','Other Handmade Products':'अन्य हस्तनिर्मित उत्पाद',products:'उत्पाद',enquirySent:'आपकी पूछताछ भेज दी गई।',sent:'भेजी गई',viewed:'देखी गई',responded:'जवाब मिला',processing:'तैयार हो रहा है',shipped:'भेज दिया',delivered:'पहुँचा दिया',orderLabel:'ऑर्डर',visualAnalysis:'तस्वीर में दिखी जानकारी'},
  'ml-IN':{edit:'തിരുത്തുക',delete:'നീക്കുക',optional:'ഐച്ഛികം',home:'ഹോം',decrease:'എണ്ണം കുറയ്ക്കുക',increase:'എണ്ണം കൂട്ടുക',remove:'നീക്കുക',photoEnhanceFailed:'ചിത്രം മെച്ചപ്പെടുത്താൻ കഴിഞ്ഞില്ല.',enhancedPreview:'മെച്ചപ്പെടുത്തിയ ചിത്രം കാണുക',acceptPhoto:'മെച്ചപ്പെടുത്തിയ ചിത്രം ഉപയോഗിക്കുക',photoAvailable:'യഥാർത്ഥ ചിത്രം സുരക്ഷിതമാണ്.',saved:'സേവ് ചെയ്തവ',myEnquiries:'എന്റെ അന്വേഷണങ്ങൾ',saveProduct:'ഉൽപ്പന്നം സേവ് ചെയ്യുക',savedRemove:'സേവ് ചെയ്തതിൽ നിന്ന് നീക്കുക',savedAdded:'ഉൽപ്പന്നം സേവ് ചെയ്തു',savedRemoved:'സേവ് ചെയ്തവയിൽ നിന്ന് നീക്കി',savedEmpty:'സേവ് ചെയ്ത ഉൽപ്പന്നങ്ങളില്ല',savedHint:'കരകൗശലക്കാരനോട് ചോദിക്കാനുള്ള ഉൽപ്പന്നങ്ങൾ സേവ് ചെയ്യൂ.',b2bMarketplace:'കരകൗശല ഉൽപ്പന്നങ്ങൾ കണ്ടെത്തൂ · ബൾക്ക് ഓർഡർ ചോദിക്കൂ',productsByArtisan:'ഈ കരകൗശലക്കാരന്റെ ഉൽപ്പന്നങ്ങൾ',Handloom:'കൈത്തറി',Handicrafts:'കരകൗശല വസ്തുക്കൾ','Bamboo Craft':'മുള കരകൗശലം','Wood Craft':'മര കരകൗശലം',Bags:'ബാഗുകൾ',Traditional:'പരമ്പരാഗതം','Other Handmade Products':'മറ്റ് കൈകൊണ്ട് നിർമ്മിച്ചവ',products:'ഉൽപ്പന്നങ്ങൾ',enquirySent:'നിങ്ങളുടെ അന്വേഷണം അയച്ചു.',sent:'അയച്ചു',viewed:'കണ്ടു',responded:'മറുപടി ലഭിച്ചു',processing:'തയ്യാറാക്കുന്നു',shipped:'അയച്ചു',delivered:'എത്തി',orderLabel:'ഓർഡർ',visualAnalysis:'ചിത്രത്തിൽ കാണുന്ന വിവരം'},
};
Object.assign(sharedCopy['hi-IN'], {artisanProducts:'कारीगरों के उत्पाद', recommendedProducts:'आपके लिए सुझाव'});
Object.assign(sharedCopy['ml-IN'], {artisanProducts:'കരകൗശലക്കാരുടെ ഉൽപ്പന്നങ്ങൾ', recommendedProducts:'നിങ്ങൾക്കായി ശുപാർശ ചെയ്തത്'});
Object.assign(sharedCopy['en-IN'], {materialFilter:'Material',artisanFilter:'Artisan',availabilityFilter:'Only in stock',minPrice:'Minimum price',maxPrice:'Maximum price',businessName:'Business name',businessType:'Business type',contactInfo:'Phone or email',contactHint:'How can the artisan reach you?',interests:'Product interests',buyers:'Buyers',cancelled:'Cancelled',buyerLabel:'Buyer',productLabel:'Product',statusLabel:'Status',markCancelled:'Cancel order',wholesale:'Wholesale opportunities',recentEnquiries:'Recent enquiries'});
Object.assign(sharedCopy['ta-IN'], {materialFilter:'பொருள்',artisanFilter:'கைவினைஞர்',availabilityFilter:'கையிருப்பில் உள்ளவை மட்டும்',minPrice:'குறைந்தபட்ச விலை',maxPrice:'அதிகபட்ச விலை',businessName:'வணிகப் பெயர்',businessType:'வணிக வகை',contactInfo:'தொலைபேசி அல்லது மின்னஞ்சல்',contactHint:'கைவினைஞர் உங்களை எவ்வாறு தொடர்புகொள்வார்?',interests:'விருப்பமான பொருட்கள்',buyers:'வாங்குபவர்கள்',cancelled:'ரத்து செய்யப்பட்டது',buyerLabel:'வாங்குபவர்',productLabel:'பொருள்',statusLabel:'நிலை',markCancelled:'ஆர்டரை ரத்து செய்',wholesale:'மொத்த விற்பனை வாய்ப்புகள்',recentEnquiries:'சமீபத்திய விசாரணைகள்'});
Object.assign(sharedCopy['hi-IN'], {materialFilter:'सामग्री',artisanFilter:'कारीगर',availabilityFilter:'केवल उपलब्ध उत्पाद',minPrice:'न्यूनतम कीमत',maxPrice:'अधिकतम कीमत',businessName:'व्यवसाय का नाम',businessType:'व्यवसाय का प्रकार',contactInfo:'फोन या ईमेल',contactHint:'कारीगर आपसे कैसे संपर्क करें?',interests:'पसंदीदा उत्पाद',buyers:'खरीदार',cancelled:'रद्द',buyerLabel:'खरीदार',productLabel:'उत्पाद',statusLabel:'स्थिति',markCancelled:'ऑर्डर रद्द करें',wholesale:'थोक अवसर',recentEnquiries:'हाल की पूछताछ'});
Object.assign(sharedCopy['ml-IN'], {materialFilter:'വസ്തു',artisanFilter:'കരകൗശലക്കാരൻ',availabilityFilter:'സ്റ്റോക്കിലുള്ളവ മാത്രം',minPrice:'കുറഞ്ഞ വില',maxPrice:'കൂടിയ വില',businessName:'ബിസിനസ് പേര്',businessType:'ബിസിനസ് തരം',contactInfo:'ഫോൺ അല്ലെങ്കിൽ ഇമെയിൽ',contactHint:'കരകൗശലക്കാരൻ നിങ്ങളെ എങ്ങനെ ബന്ധപ്പെടും?',interests:'ഇഷ്ടമുള്ള ഉൽപ്പന്നങ്ങൾ',buyers:'വാങ്ങുന്നവർ',cancelled:'റദ്ദാക്കി',buyerLabel:'വാങ്ങുന്നയാൾ',productLabel:'ഉൽപ്പന്നം',statusLabel:'നില',markCancelled:'ഓർഡർ റദ്ദാക്കുക',wholesale:'മൊത്തവ്യാപാര അവസരങ്ങൾ',recentEnquiries:'സമീപകാല അന്വേഷണങ്ങൾ'});
Object.assign(sharedCopy['en-IN'],{addProduct:'Add product',pricing:'Pricing',categories:'Categories',search:'Search',lastActivity:'Last activity',enquiryCount:'Enquiries',orderCount:'Orders',noBuyers:'Buyer activity will appear here when someone enquires or orders.',businessNameLabel:'Business',materialCost:'Material cost',labourCost:'Labour cost',makingTime:'Making time',getSuggestion:'Get price suggestion',suggestedRange:'Suggested range',applyPrice:'Use suggested price',priceApplied:'Suggested price saved',priceProduct:'Product to price',browseCategories:'Browse products by craft',craftType:'Craft type',pricingExplanation:'This estimate uses your material and labour costs with an indicative craft-category range. Check local costs before setting your price.'});
Object.assign(sharedCopy['ta-IN'],{addProduct:'பொருள் சேர்',pricing:'விலை',categories:'வகைகள்',search:'தேடு',lastActivity:'கடைசி செயல்',enquiryCount:'விசாரணைகள்',orderCount:'ஆர்டர்கள்',noBuyers:'வாங்குபவர்கள் விசாரிக்கும்போது அல்லது ஆர்டர் செய்யும்போது இங்கே தெரியும்.',businessNameLabel:'வணிகம்',materialCost:'பொருள் செலவு',labourCost:'உழைப்பு செலவு',makingTime:'செய்யும் நேரம்',getSuggestion:'விலை பரிந்துரை',suggestedRange:'பரிந்துரை வரம்பு',applyPrice:'இந்த விலையைப் பயன்படுத்து',priceApplied:'பரிந்துரைக்கப்பட்ட விலை சேமிக்கப்பட்டது',priceProduct:'விலை கணக்கிடும் பொருள்',browseCategories:'கைவினை வகைகளில் பொருட்களைப் பாருங்கள்',craftType:'கைவினை வகை',pricingExplanation:'இந்த மதிப்பீடு உங்கள் பொருள் மற்றும் உழைப்புச் செலவுகளையும் கைவினை வகைக்கான தோராயமான விலை வரம்பையும் பயன்படுத்துகிறது. விலையை நிர்ணயிக்கும் முன் உள்ளூர் செலவுகளைச் சரிபார்க்கவும்.'});
Object.assign(sharedCopy['hi-IN'],{addProduct:'उत्पाद जोड़ें',pricing:'कीमत',categories:'श्रेणियाँ',search:'खोजें',lastActivity:'आखिरी गतिविधि',enquiryCount:'पूछताछ',orderCount:'ऑर्डर',noBuyers:'खरीदार पूछताछ या ऑर्डर करेंगे तो यहाँ दिखेंगे।',businessNameLabel:'व्यवसाय',materialCost:'सामग्री लागत',labourCost:'मजदूरी लागत',makingTime:'बनाने का समय',getSuggestion:'कीमत सुझाएं',suggestedRange:'सुझाई गई सीमा',applyPrice:'सुझाई कीमत अपनाएं',priceApplied:'सुझाई कीमत सहेजी गई',priceProduct:'कीमत वाला उत्पाद',browseCategories:'शिल्प के अनुसार उत्पाद देखें',craftType:'शिल्प का प्रकार',pricingExplanation:'यह अनुमान आपकी सामग्री और मजदूरी लागत के साथ शिल्प श्रेणी की संकेतात्मक सीमा का उपयोग करता है। कीमत तय करने से पहले स्थानीय लागत जाँचें।'});
Object.assign(sharedCopy['ml-IN'],{addProduct:'ഉൽപ്പന്നം ചേർക്കുക',pricing:'വില',categories:'വിഭാഗങ്ങൾ',search:'തിരയുക',lastActivity:'അവസാന പ്രവർത്തനം',enquiryCount:'അന്വേഷണങ്ങൾ',orderCount:'ഓർഡറുകൾ',noBuyers:'വാങ്ങുന്നവർ അന്വേഷിക്കുകയോ ഓർഡർ ചെയ്യുകയോ ചെയ്യുമ്പോൾ ഇവിടെ കാണാം.',businessNameLabel:'ബിസിനസ്',materialCost:'വസ്തു ചെലവ്',labourCost:'തൊഴിൽ ചെലവ്',makingTime:'നിർമ്മാണ സമയം',getSuggestion:'വില നിർദ്ദേശിക്കുക',suggestedRange:'നിർദ്ദേശിച്ച പരിധി',applyPrice:'നിർദ്ദേശിച്ച വില ഉപയോഗിക്കുക',priceApplied:'നിർദ്ദേശിച്ച വില സേവ് ചെയ്തു',priceProduct:'വില നിശ്ചയിക്കേണ്ട ഉൽപ്പന്നം',browseCategories:'കരകൗശല വിഭാഗങ്ങൾ അനുസരിച്ച് ഉൽപ്പന്നങ്ങൾ കാണുക',craftType:'കരകൗശല തരം',pricingExplanation:'ഈ കണക്ക് നിങ്ങളുടെ വസ്തു-തൊഴിൽ ചെലവുകളും കരകൗശല വിഭാഗത്തിന്റെ ഏകദേശ വിലപരിധിയും ഉപയോഗിക്കുന്നു. വില നിശ്ചയിക്കുന്നതിന് മുമ്പ് പ്രാദേശിക ചെലവുകൾ പരിശോധിക്കുക.'});
Object.assign(sharedCopy['en-IN'],{productPublished:'Product published successfully. It is now available in the marketplace.',productUpdated:'Product updated successfully.',changePrice:'Change price',updateStock:'Update stock'});
Object.assign(sharedCopy['ta-IN'],{productPublished:'பொருள் வெற்றிகரமாக வெளியிடப்பட்டது. இது இப்போது சந்தையில் கிடைக்கிறது.',productUpdated:'பொருள் வெற்றிகரமாக புதுப்பிக்கப்பட்டது.',changePrice:'விலையை மாற்று',updateStock:'இருப்பை மாற்று'});
Object.assign(sharedCopy['hi-IN'],{productPublished:'उत्पाद सफलतापूर्वक प्रकाशित हुआ। यह अब बाज़ार में उपलब्ध है।',productUpdated:'उत्पाद सफलतापूर्वक अपडेट हुआ।',changePrice:'कीमत बदलें',updateStock:'स्टॉक बदलें'});
Object.assign(sharedCopy['ml-IN'],{productPublished:'ഉൽപ്പന്നം വിജയകരമായി പ്രസിദ്ധീകരിച്ചു. ഇപ്പോൾ വിപണിയിൽ ലഭ്യമാണ്.',productUpdated:'ഉൽപ്പന്നം വിജയകരമായി പുതുക്കി.',changePrice:'വില മാറ്റുക',updateStock:'സ്റ്റോക്ക് മാറ്റുക'});
export const getAppCopy = language => ({...(messages[language] || messages['en-IN']),...sharedCopy[language]});
