import React from 'react';
import { ProductPhoto, VoiceAssistant } from './artisan-tools.jsx';

const stepper=(n)=><div className="stepper">{[1,2,3].map((x)=><React.Fragment key={x}>{x>1&&<i/>}<b className={x===n?'current':x<n?'done':''}>{x<n?'✓':`0${x}`} <span>{['Details','AI Catalog','Review'][x-1]}</span></b></React.Fragment>)}</div>;

export function ProductDetailsForm({ draft, setDraft, photo, setPhoto, sourcePhoto, setSourcePhoto, onStatus, onSpeak, onTranscribe, onInterviewAnswer, onInterviewComplete, onActiveChange, onAnalyzeImage, onRemoveBackground, onSuggestPricing, voiceActive, catalogBusy, onContinue }) {
  return <div className="form-content">{stepper(1)}<div className="form-card"><div className="form-heading"><small>STEP 1 OF 3</small><h2>Tell us about your craft</h2><p>Choose a language and tap the microphone. The assistant will ask five questions and fill in your details.</p></div>
    <VoiceAssistant onSpeak={onSpeak} onTranscribe={onTranscribe} onAnswer={onInterviewAnswer} onComplete={onInterviewComplete} onActiveChange={onActiveChange}/>
    <ProductPhoto photo={photo} setPhoto={setPhoto} sourcePhoto={sourcePhoto} setSourcePhoto={setSourcePhoto} onAnalyzeImage={onAnalyzeImage} onRemoveBackground={onRemoveBackground} onStatus={onStatus}/>
    <label className="field-label">Product name <i>*</i><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="e.g. Hand-painted terracotta vase" required/></label>
    <label className="field-label">Category <i>*</i><select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{['Pottery','Textiles','Home Decor','Woodwork','Jewellery','Other'].map(x=><option key={x}>{x}</option>)}</select></label>
    <div className="field-row"><label className="field-label">Material<input value={draft.material||''} onChange={e=>setDraft({...draft,material:e.target.value})} placeholder="e.g. cotton, clay, wood"/></label><label className="field-label">Color<input value={draft.color||''} onChange={e=>setDraft({...draft,color:e.target.value})} placeholder="Only if known"/></label></div>
    <div className="field-row"><label className="field-label">Size or dimensions<input value={draft.size||''} onChange={e=>setDraft({...draft,size:e.target.value})} placeholder="Optional"/></label><label className="field-label">Making time<input value={draft.production_time||''} onChange={e=>setDraft({...draft,production_time:e.target.value})} placeholder="e.g. 3 days"/></label></div>
    <label className="field-label">How it was made<input value={draft.making_method||''} onChange={e=>setDraft({...draft,making_method:e.target.value})} placeholder="Optional technique or tradition"/></label>
    <div className="field-row"><label className="field-label">Your price <i>*</i><div className="currency-input"><span>₹</span><input type="number" min="1" value={draft.price} onChange={e=>setDraft({...draft,price:e.target.value})} placeholder="0" required/></div></label><label className="field-label">Stock available<input type="number" min="0" value={draft.stock} onChange={e=>setDraft({...draft,stock:e.target.value})} placeholder="0"/></label></div>
    <label className="field-label">Materials and labour cost (₹)<input type="number" min="0" value={draft.production_cost||''} onChange={e=>setDraft({...draft,production_cost:e.target.value})} placeholder="Optional, used for a price range"/></label>
    <button type="button" className="button-secondary" onClick={onSuggestPricing}>Get price suggestion</button>
    {draft.suggestedLow&&<div className="analysis-card"><div><span>{draft.suggestionSource||'Indicative price range'}</span><b>₹{Number(draft.suggestedLow).toLocaleString('en-IN')}–₹{Number(draft.suggestedHigh).toLocaleString('en-IN')}</b><small>{draft.priceExplanation||'Estimate based on your costs and a category reference. Adjust it to your local market.'}</small></div><span className="trend-badge">Suggested ₹{Number(draft.suggestedPrice).toLocaleString('en-IN')}</span></div>}
    <label className="field-label">Product story<textarea rows="3" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="How did you make it? Which materials and special techniques did you use?"/></label>
    <label className="field-label">Listing status<select value={draft.status||'Active'} onChange={e=>setDraft({...draft,status:e.target.value})}><option value="Active">Publish when I finish</option><option value="Draft">Save as a draft</option></select><small>Only active listings appear to buyers.</small></label>
      <div className="form-actions"><button className="button-primary" disabled={catalogBusy||voiceActive||!draft.name.trim()||!draft.price||Number(draft.price)<1} onClick={onContinue}>{voiceActive?'Finish the voice interview first':catalogBusy?'Generating catalog…':'Continue to catalog'} <span>→</span></button></div>
  </div></div>;
}

export function ProductVoiceForm({ draft, setDraft, transcript, catalogBusy, onStatus, onGenerateCatalog, onBack, onContinue }) {
  const prepareBilingual=async()=>{const result=await onGenerateCatalog();onStatus(result?'Bilingual catalog generated. Review and edit both versions.':'Unable to generate the catalog. Please try again.');};
  const continueToReview=async()=>{if(!draft.description_en||!draft.description_hi){const result=await onGenerateCatalog();if(!result)return;}onContinue();};
  return <div className="form-content">{stepper(2)}<div className="form-card"><div className="form-heading"><small>STEP 2 OF 3</small><h2>Build your product story</h2><p>Describe how you made the product and which materials or techniques you used. Review the English and Hindi catalog drafts.</p></div>
    <div className="catalog-transcript"><b>English answers from the voice interview</b><p dir="auto">{transcript||'Your English answers will appear here after the voice interview.'}</p></div>
    <label className="field-label">How it was made and materials used<textarea rows="4" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="Tell buyers how you made it, which materials you used, and the techniques or traditions behind it."/></label>
    <div className="bilingual-heading"><div><small>MARKETPLACE DESCRIPTION</small><b>English & Hindi</b></div><button type="button" className="button-secondary" onClick={prepareBilingual} disabled={catalogBusy}>{catalogBusy?'Generating…':'Create bilingual drafts'}</button></div>
    <div className="bilingual-edit-grid"><label className="field-label"><span>English <small>🇬🇧</small></span><textarea rows="5" value={draft.description_en||''} onChange={e=>setDraft({...draft,description_en:e.target.value})} placeholder="English product description"/>{draft.description_en&&<button type="button" onClick={()=>window.speechSynthesis?.speak(new SpeechSynthesisUtterance(draft.description_en))}>▶ Listen in English</button>}</label><label className="field-label"><span>Hindi <small>हिं</small></span><textarea rows="5" dir="auto" value={draft.description_hi||''} onChange={e=>setDraft({...draft,description_hi:e.target.value})} placeholder="हिंदी में उत्पाद का विवरण"/>{draft.description_hi&&<button type="button" onClick={()=>{const u=new SpeechSynthesisUtterance(draft.description_hi);u.lang='hi-IN';window.speechSynthesis?.speak(u)}}>▶ हिंदी में सुनें</button>}</label></div>
    <p className="translation-note">Review both language versions for accuracy. You can dictate each one by selecting its description field in the voice assistant.</p>
    <div className="form-actions split"><button className="button-secondary" onClick={onBack}>← Back</button><button className="button-primary" onClick={continueToReview} disabled={catalogBusy}>Review product →</button></div>
  </div></div>;
}

export function ProductReviewForm({ draft, photo, editing, onBack, onPublish }) {
  const [photoReviewOpen,setPhotoReviewOpen]=React.useState(false);
  return <div className="form-content">{stepper(3)}<div className="form-card"><div className="form-heading"><small>STEP 3 OF 3</small><h2>Your product listing</h2><p>Check the details and both language descriptions before publishing.</p></div>
    <div className="analysis-card"><div><span>✦ {draft.suggestionSource||'Indicative price range'}</span><b>{draft.suggestedLow?`₹${Number(draft.suggestedLow).toLocaleString('en-IN')}–₹${Number(draft.suggestedHigh).toLocaleString('en-IN')}`:`₹${Number(draft.suggestedPrice||draft.price||0).toLocaleString('en-IN')}`}</b><small>{draft.priceExplanation||'Review any estimate against your costs and local market.'}</small></div><span className="trend-badge">Your price: ₹ {Number(draft.price||0).toLocaleString('en-IN')}</span></div>
    <div className="review-product"><button type="button" className="review-art review-art-button" onClick={()=>photo&&setPhotoReviewOpen(true)} disabled={!photo} aria-label="Review product listing photo">{photo?<img src={photo} alt="Cleaned product"/>:<span>🏺</span>}</button><div><small>{draft.category}</small><h3>{draft.name||'Your handmade creation'}</h3><b>₹ {Number(draft.price||0).toLocaleString('en-IN')}</b><span>Stock: {draft.stock||'—'}</span>{draft.material&&<span>Material: {draft.material}</span>}{draft.color&&<span>Color: {draft.color}</span>}{draft.size&&<span>Size: {draft.size}</span>}</div></div>
    {photoReviewOpen&&<div className="photo-review-backdrop" role="presentation" onClick={()=>setPhotoReviewOpen(false)}><section className="photo-review-dialog listing-photo-dialog" role="dialog" aria-modal="true" aria-labelledby="listing-photo-title" onClick={event=>event.stopPropagation()}><button type="button" className="photo-review-close" onClick={()=>setPhotoReviewOpen(false)} aria-label="Close photo review">×</button><h2 id="listing-photo-title">Marketplace photo preview</h2><p>This is how the cleaned product photo will appear in your listing.</p><img className="listing-photo-large" src={photo} alt={`${draft.name||'Product'} listing image on a white background`}/><button type="button" className="button-primary" onClick={()=>setPhotoReviewOpen(false)}>Done reviewing</button></section></div>}
    {draft.keywords?.length>0&&<div className="product-tags catalog-keywords">{draft.keywords.map(keyword=><span key={keyword}>{keyword}</span>)}</div>}
    <div className="bilingual-preview"><h3>English description</h3><p>{draft.description_en||'Add an English description.'}</p><h3 lang="hi">उत्पाद का हिंदी विवरण</h3><p lang="hi" dir="auto">{draft.description_hi||'हिंदी में विवरण जोड़ें।'}</p></div>
    <div className="form-actions split"><button className="button-secondary" onClick={onBack}>← Edit descriptions</button><button className="button-primary" onClick={onPublish}>{editing?'Save changes':draft.status==='Draft'?'Save draft':'Publish product'}</button></div>
  </div></div>;
}
