import React, { useState } from 'react';

export function BusinessAssistant({ onAsk, ui={}, language='en-IN' }) {
  const [question, setQuestion] = useState('');
  const [answer, setAnswer] = useState('');
  const [busy, setBusy] = useState(false);
  const ask = async value => {
    const prompt = String(value || question).trim();
    if (!prompt || busy) return;
    setQuestion(prompt);
    setBusy(true);
    try { const result = await onAsk(prompt); setAnswer(result.answer || ui.error || 'I could not find an answer.'); }
    catch (error) { setAnswer(error.message || ui.error || 'The business assistant is unavailable.'); }
    finally { setBusy(false); }
  };
  const listen = () => {
    const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (!Recognition) { setAnswer('Voice input is not available in this browser. Please type your question.'); return; }
    const recognition = new Recognition(); recognition.lang = language; recognition.interimResults = false;
    recognition.onresult = event => ask(event.results[0][0].transcript);
    recognition.onerror = () => setAnswer('I could not hear that. Please try again or type your question.');
    recognition.start();
  };
  const prompts=language==='ta-IN'?['என்னிடம் எத்தனை பொருட்கள் உள்ளன?','கையிருப்பு குறைவான பொருட்கள் எவை?','நிலுவை விசாரணைகளைக் காட்டு']:language==='hi-IN'?['मेरे पास कितने उत्पाद हैं?','किन उत्पादों का स्टॉक कम है?','लंबित पूछताछ दिखाएं']:language==='ml-IN'?['എനിക്ക് എത്ര ഉൽപ്പന്നങ്ങളുണ്ട്?','സ്റ്റോക്ക് കുറവുള്ള ഉൽപ്പന്നങ്ങൾ ഏവ?','കാത്തിരിക്കുന്ന അന്വേഷണങ്ങൾ കാണിക്കുക']:['How many products do I have?','Which products have low stock?','Show my pending enquiries'];
  const copy=language==='ta-IN'?{title:'வணிக உதவியாளர்',ask:'மார்டிசனிடம் கேளுங்கள்',hint:'பொருட்கள், இருப்பு, விற்பனை அல்லது விசாரணைகள் பற்றி கேளுங்கள்.',placeholder:'என்னிடம் எத்தனை பொருட்கள் உள்ளன?',checking:'சரிபார்க்கிறது…',listen:'கேளுங்கள்',unavailable:'குரல் உள்ளீடு கிடைக்கவில்லை. தட்டச்சு செய்யவும்.'}:language==='hi-IN'?{title:'आपका व्यवसाय सहायक',ask:'मार्टिसन से पूछें',hint:'उत्पाद, स्टॉक, बिक्री या पूछताछ के बारे में पूछें।',placeholder:'मेरे पास कितने उत्पाद हैं?',checking:'जाँच रहे हैं…',listen:'सुनें',unavailable:'आवाज़ उपलब्ध नहीं है। कृपया लिखें।'}:language==='ml-IN'?{title:'ബിസിനസ് സഹായി',ask:'മാർട്ടിസനോട് ചോദിക്കൂ',hint:'ഉൽപ്പന്നം, സ്റ്റോക്ക്, വിൽപ്പന, അന്വേഷണങ്ങൾ എന്നിവ ചോദിക്കൂ.',placeholder:'എനിക്ക് എത്ര ഉൽപ്പന്നങ്ങളുണ്ട്?',checking:'പരിശോധിക്കുന്നു…',listen:'കേൾക്കുക',unavailable:'ശബ്ദ ഇൻപുട്ട് ലഭ്യമല്ല. ദയവായി ടൈപ്പ് ചെയ്യുക.'}:{title:'YOUR BUSINESS ASSISTANT',ask:'Ask Martisan',hint:'Ask about products, stock, sales, enquiries, or pricing.',placeholder:'How many products do I have?',checking:'Checking…',listen:'Listen',unavailable:'Voice input is not available in this browser. Please type your question.'};
  return <section className="form-card business-assistant" lang={language}><div className="section-heading"><div><small>{copy.title}</small><h2>{copy.ask}</h2></div><span>✦</span></div><p>{copy.hint}</p><div className="assistant-input"><input value={question} onChange={event=>setQuestion(event.target.value)} onKeyDown={event=>event.key==='Enter'&&ask()} placeholder={copy.placeholder} aria-label={copy.ask}/><button type="button" className="button-secondary" onClick={listen} aria-label={copy.listen}>🎙</button><button type="button" className="button-primary" onClick={()=>ask()} disabled={busy||!question.trim()}>{busy?copy.checking:(ui.search||'Ask')}</button></div>{answer&&<div className="assistant-answer" role="status"><p>{answer}</p><button type="button" className="button-secondary" onClick={()=>{if(window.speechSynthesis){const utterance=new SpeechSynthesisUtterance(answer);utterance.lang=language;const voices=window.speechSynthesis.getVoices();utterance.voice=voices.find(item=>item.lang?.toLowerCase()===language.toLowerCase())||voices.find(item=>item.lang?.toLowerCase().startsWith(language.split('-')[0].toLowerCase()))||null;window.speechSynthesis.speak(utterance)}}}>▶ {copy.listen}</button></div>}<div className="assistant-suggestions">{prompts.map(item=><button type="button" key={item} onClick={()=>ask(item)}>{item}</button>)}</div></section>;
}

export function SellerInsights({ dashboard, enquiries, onEnquiryStatus, onConvertEnquiry, onOpenEnquiries, ui={}, language='en-IN' }) {
  const data = dashboard || {};
  const text=language==='ta-IN'?{total:'மொத்த பொருட்கள்',active:'செயலில் உள்ளவை',stock:'கையிருப்பு',enquiries:'புதிய விசாரணைகள்',orders:'நிறைவேற்ற வேண்டிய ஆர்டர்கள்',sales:'வழங்கிய விற்பனை',buyers:'வாங்குபவர்கள்',inventory:'கையிருப்பு சரிபார்ப்பு',low:'குறைந்த கையிருப்பு',none:'குறைந்த கையிருப்பு பொருட்கள் இல்லை.',popular:'பிரபலமான பொருட்கள்',requests:'வாங்குபவர் கோரிக்கைகள்',recent:'சமீபத்திய விசாரணைகள்',all:'அனைத்தையும் பார்க்கவும்',left:'மீதம்',sold:'விற்றது',pending:'காத்திருப்பில் குறிக்கவும்',accept:'ஏற்று ஆர்டர் உருவாக்கவும்',noEnq:'வாங்குபவர் விசாரணைகள் இல்லை.'}:language==='hi-IN'?{total:'कुल उत्पाद',active:'सक्रिय सूची',stock:'उपलब्ध स्टॉक',enquiries:'नई पूछताछ',orders:'पूरा करने के ऑर्डर',sales:'डिलीवरी बिक्री',buyers:'खरीदार',inventory:'स्टॉक जाँच',low:'कम स्टॉक',none:'कम स्टॉक वाला उत्पाद नहीं है।',popular:'लोकप्रिय उत्पाद',requests:'खरीदार अनुरोध',recent:'हाल की पूछताछ',all:'सभी देखें',left:'बाकी',sold:'बिके',pending:'प्रतीक्षा में रखें',accept:'स्वीकार कर ऑर्डर बनाएं',noEnq:'खरीदार की पूछताछ नहीं है।'}:language==='ml-IN'?{total:'ആകെ ഉൽപ്പന്നങ്ങൾ',active:'സജീവ ലിസ്റ്റിങ്ങുകൾ',stock:'ലഭ്യമായ സ്റ്റോക്ക്',enquiries:'പുതിയ അന്വേഷണങ്ങൾ',orders:'പൂർത്തിയാക്കേണ്ട ഓർഡറുകൾ',sales:'വിതരണം ചെയ്ത വിൽപ്പന',buyers:'വാങ്ങുന്നവർ',inventory:'സ്റ്റോക്ക് പരിശോധിക്കുക',low:'സ്റ്റോക്ക് കുറവ്',none:'സ്റ്റോക്ക് കുറഞ്ഞ ഉൽപ്പന്നങ്ങളില്ല.',popular:'ജനപ്രിയ ഉൽപ്പന്നങ്ങൾ',requests:'വാങ്ങുന്നവരുടെ അഭ്യർത്ഥനകൾ',recent:'സമീപകാല അന്വേഷണങ്ങൾ',all:'എല്ലാം കാണുക',left:'ബാക്കി',sold:'വിറ്റു',pending:'കാത്തിരിപ്പായി അടയാളപ്പെടുത്തുക',accept:'അംഗീകരിച്ച് ഓർഡർ ഉണ്ടാക്കുക',noEnq:'വാങ്ങുന്നവരുടെ അന്വേഷണങ്ങളില്ല.'}:{total:'TOTAL PRODUCTS',active:'ACTIVE LISTINGS',stock:'AVAILABLE STOCK',enquiries:'NEW ENQUIRIES',orders:'ORDERS TO FULFIL',sales:'DELIVERED SALES',buyers:'BUYERS',inventory:'INVENTORY CHECK',low:'Running low',none:'No products are running low.',popular:'Popular products',requests:'BUYER REQUESTS',recent:'Recent enquiries',all:'View all',left:'left',sold:'sold',pending:'Mark pending',accept:'Accept & create order',noEnq:'No buyer enquiries yet.'};
  return <><div className="seller-stats business-stats" lang={language}><div><small>{text.total}</small><b>{data.totalProducts||0}</b></div><div><small>{text.active}</small><b>{data.activeProducts||0}</b></div><div><small>{text.stock}</small><b>{data.availableStock||0}</b></div><div><small>{text.enquiries}</small><b>{data.newEnquiries||0}</b></div><div><small>{text.orders}</small><b>{data.pendingOrders||0}</b></div><div><small>{text.sales}</small><b>₹{Number(data.sales||0).toLocaleString('en-IN')}</b></div><div><small>{text.buyers}</small><b>{data.buyers||0}</b></div></div><div className="business-panels" lang={language}><section className="form-card"><div className="section-heading"><div><small>{text.inventory}</small><h2>{text.low}</h2></div></div>{data.lowStock?.length?data.lowStock.map(product=><p className="business-list-item" key={product.id}><b>{product.name}</b><span>{product.stock} {text.left}</span></p>):<p className="business-muted">{text.none}</p>}<h3>{text.popular}</h3>{data.popularProducts?.slice(0,3).map(product=><p className="business-list-item" key={product.id}><b>{product.name}</b><span>{product.unitsSold} {text.sold}</span></p>)}</section><section className="form-card"><div className="section-heading"><div><small>{text.requests}</small><h2>{text.recent}</h2></div><button className="button-secondary" onClick={onOpenEnquiries}>{text.all}</button></div>{enquiries?.length?enquiries.slice(0,3).map(item=><div className="business-enquiry" key={item.id}><b>{item.buyer_name} · {item.buyer_type}</b><span>{item.quantity} × {item.product_name} · {item.status}</span>{['New','Pending'].includes(item.status)&&<div><button className="button-secondary" onClick={()=>onEnquiryStatus(item.id,'Pending')}>{text.pending}</button><button className="button-primary" onClick={()=>onConvertEnquiry(item.id)}>{text.accept}</button></div>}</div>):<p className="business-muted">{text.noEnq}</p>}</section></div></>;
}

export function SellerRecentActivity({orders=[],enquiries=[],products=[],ui={},language='en-IN',onOpen}) {
  const copy=language==='ta-IN'?{title:'சமீபத்திய செயல்பாடு',orders:'சமீபத்திய ஆர்டர்கள்',enquiries:'சமீபத்திய விசாரணைகள்',products:'சமீபத்திய பொருட்கள்',none:'இன்னும் செயல்பாடு இல்லை'}:language==='hi-IN'?{title:'हाल की गतिविधि',orders:'हाल के ऑर्डर',enquiries:'हाल की पूछताछ',products:'हाल के उत्पाद',none:'अभी कोई गतिविधि नहीं'}:language==='ml-IN'?{title:'സമീപകാല പ്രവർത്തനം',orders:'സമീപകാല ഓർഡറുകൾ',enquiries:'സമീപകാല അന്വേഷണങ്ങൾ',products:'സമീപകാല ഉൽപ്പന്നങ്ങൾ',none:'ഇപ്പോൾ പ്രവർത്തനമില്ല'}:{title:'Recent activity',orders:'Recent orders',enquiries:'Recent enquiries',products:'Recent products',none:'No activity yet'};
  const hasActivity=orders.length||enquiries.length||products.length;
  return <section className="form-card seller-recent-activity" lang={language}><div className="section-heading"><div><small>{ui.yourShop}</small><h2>{copy.title}</h2></div></div>{!hasActivity?<p className="business-muted">{copy.none}</p>:<div className="seller-activity-columns">{orders.slice(0,3).length>0&&<section><h3>{copy.orders}</h3>{orders.slice(0,3).map(order=><button className="buyer-activity-row" key={order.id} onClick={()=>onOpen('orders')}><b>{order.buyer_name||order.id}</b><span>{orderStatus(order.status,ui)} · ₹{Number(order.total||0).toLocaleString('en-IN')}</span></button>)}</section>}{enquiries.slice(0,3).length>0&&<section><h3>{copy.enquiries}</h3>{enquiries.slice(0,3).map(item=><button className="buyer-activity-row" key={item.id} onClick={()=>onOpen('enquiries')}><b>{item.buyer_name} · {item.product_name}</b><span>{item.quantity} · {item.status}</span></button>)}</section>}{products.slice(0,3).length>0&&<section><h3>{copy.products}</h3>{products.slice(0,3).map(product=><button className="buyer-activity-row" key={product.id} onClick={()=>onOpen('products')}><b>{product.name}</b><span>{ui.active||product.status} · ₹{Number(product.price||0).toLocaleString('en-IN')}</span></button>)}</section>}</div>}</section>;
}

function orderStatus(status,ui){return ({Processing:ui.processing,Shipped:ui.shipped,Delivered:ui.delivered,Cancelled:ui.cancelled})[status]||status||''}

export function BuyerEnquiryForm({ product, onSubmit, ui={}, language='en-IN', initialBuyerName='' }) {
  const [buyerName, setBuyerName] = useState(initialBuyerName);
  const [buyerType, setBuyerType] = useState('Retailer');
  const [quantity, setQuantity] = useState('10');
  const [requestedPrice, setRequestedPrice] = useState('');
  const [contact, setContact] = useState('');
  const [message, setMessage] = useState('');
  const [busy, setBusy] = useState(false);
  const submit = async event => {
    event.preventDefault();
    setBusy(true);
    try { await onSubmit({product_id:product.id,buyer_name:buyerName,buyer_type:buyerType,quantity:Number(quantity),requested_price:requestedPrice?Number(requestedPrice):null,message,contact}); }
    finally { setBusy(false); }
  };
  const types=[['Retailer',ui.retailer],['Wholesaler',ui.wholesaler],['Bulk buyer',ui.bulkBuyer],['Online seller',ui.onlineSeller],['Corporate buyer',ui.corporateBuyer],['Procurement organization',ui.procurement]];
  return <form className="enquiry-form" onSubmit={submit} lang={language}><h3>{ui.contactArtisan} · {ui.bulkRequest}</h3><label className="field-label">{ui.yourName}<input value={buyerName} onChange={e=>setBuyerName(e.target.value)} minLength="2" required placeholder={ui.buyerName}/></label><label className="field-label">{ui.contactInfo||'Phone or email (optional)'}<input value={contact} onChange={e=>setContact(e.target.value)} maxLength="200" placeholder={ui.contactHint||'How can the artisan reach you?'}/></label><label className="field-label">{ui.buyerType}<select value={buyerType} onChange={e=>setBuyerType(e.target.value)}>{types.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><div className="field-row"><label className="field-label">{ui.quantity}<input type="number" min="1" max={Math.max(product.stock||1,1)} value={quantity} onChange={e=>setQuantity(e.target.value)} required/></label><label className="field-label">{ui.targetPrice}<input type="number" min="1" value={requestedPrice} onChange={e=>setRequestedPrice(e.target.value)} placeholder={ui.optional||'—'}/></label></div><label className="field-label">{ui.message}<textarea rows="2" value={message} onChange={e=>setMessage(e.target.value)} placeholder={ui.messageHint}/></label><button className="button-primary" disabled={busy||!product.stock}>{busy?ui.sending:ui.send}</button></form>;
}
